from abc import ABC, abstractmethod
from core.models import SellOffer, Match, Contract

class PlatformBase(ABC):
    name = "base"
    escrow_type = "onchain"
    @abstractmethod
    def authenticate(self): ...
    @abstractmethod
    def create_sell_offer(self, min_sats, max_sats, premium_pct, payment_methods, **kw): ...
    @abstractmethod
    def get_escrow_address(self, offer_id): ...
    @abstractmethod
    def get_active_offers(self): ...
    @abstractmethod
    def cancel_offer(self, offer_id): ...
    @abstractmethod
    def check_matches(self, offer_id): ...
    @abstractmethod
    def accept_match(self, offer_id, match_id): ...
    @abstractmethod
    def get_contracts(self): ...
    @abstractmethod
    def confirm_payment(self, contract_id): ...
    def get_platform_fee_pct(self): return 2.0
    def get_status(self): return {"name":self.name,"escrow_type":self.escrow_type}
